name: Auto tagging and release

on:
  # Triggers the workflow pull request events but only for the main and develop branch
  pull_request:
    branches:
      - main
      - develop
    types: [closed]
    paths-ignore:
      - '.github/workflows/auto_tagging.yml'

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: auto_tagging
        uses: k8-proxy/auto-tagging@v0.1.0
        with:
           GITHUBPAT: ${{secrets.GITHUBPAT}}
           main_branch_name: "main"
           develop_branch_name: "develop"